use super::*;
use reqwest::header::{HeaderMap, HeaderName, HeaderValue};

fn make_headers(pairs: &[(&str, &str)]) -> HeaderMap {
    let mut map = HeaderMap::new();
    for (k, v) in pairs {
        map.insert(
            HeaderName::from_bytes(k.as_bytes()).unwrap(),
            HeaderValue::from_str(v).unwrap(),
        );
    }
    map
}

#[test]
fn test_cloudflare_detection_by_header() {
    let headers = make_headers(&[("cf-ray", "abc123"), ("server", "cloudflare")]);
    let result = fingerprint_from_response(&headers, None, 200);
    assert!(!result.is_empty());
    let primary = result.primary().unwrap();
    assert_eq!(primary.waf_type, WafType::Cloudflare);
    assert!(primary.confidence >= 0.9);
}

#[test]
fn test_imperva_detection_by_body() {
    let headers = make_headers(&[]);
    let body = "Request blocked. Incapsula incident ID: 123456";
    let result = fingerprint_from_response(&headers, Some(body), 403);
    assert!(!result.is_empty());
    assert!(result.waf_types().contains(&&WafType::Imperva));
}

#[test]
fn test_wordfence_detection() {
    let headers = make_headers(&[]);
    let body = "This response was generated by Wordfence.";
    let result = fingerprint_from_response(&headers, Some(body), 403);
    assert!(result.waf_types().contains(&&WafType::Wordfence));
}

#[test]
fn test_aws_waf_header_detection() {
    let headers = make_headers(&[("x-amzn-waf-action", "block")]);
    let result = fingerprint_from_response(&headers, None, 403);
    assert!(result.waf_types().contains(&&WafType::AwsWaf));
    assert!(result.primary().unwrap().confidence >= 0.9);
}

#[test]
fn test_modsecurity_body_detection() {
    let headers = make_headers(&[]);
    let body = "<html><body>ModSecurity - Access Denied</body></html>";
    let result = fingerprint_from_response(&headers, Some(body), 403);
    assert!(result.waf_types().contains(&&WafType::ModSecurity));
}

#[test]
fn test_no_waf_detected() {
    let headers = make_headers(&[("server", "nginx"), ("content-type", "text/html")]);
    let result = fingerprint_from_response(&headers, Some("<html>ok</html>"), 200);
    assert!(result.is_empty());
}

#[test]
fn test_multiple_waf_detection() {
    // Cloudflare CDN + ModSecurity origin (common setup)
    let headers = make_headers(&[("cf-ray", "abc"), ("server", "cloudflare")]);
    let body = "ModSecurity Action denied";
    let result = fingerprint_from_response(&headers, Some(body), 403);
    assert!(result.waf_types().contains(&&WafType::Cloudflare));
    assert!(result.waf_types().contains(&&WafType::ModSecurity));
}

#[test]
fn test_merge_results_takes_max_confidence() {
    let mut a = WafDetectionResult {
        detected: vec![WafFingerprint {
            waf_type: WafType::Cloudflare,
            confidence: 0.5,
            evidence: "header".to_string(),
        }],
    };
    let b = WafDetectionResult {
        detected: vec![WafFingerprint {
            waf_type: WafType::Cloudflare,
            confidence: 0.9,
            evidence: "probe".to_string(),
        }],
    };
    merge_results(&mut a, b);
    assert_eq!(a.detected.len(), 1);
    assert!(a.detected[0].confidence >= 0.9);
}

#[test]
fn test_sucuri_detection() {
    let headers = make_headers(&[("x-sucuri-id", "12345")]);
    let body = "Access Denied - Sucuri Website Firewall";
    let result = fingerprint_from_response(&headers, Some(body), 403);
    assert!(result.waf_types().contains(&&WafType::Sucuri));
    assert!(result.primary().unwrap().confidence >= 0.9);
}

#[test]
fn test_fastly_detection() {
    let headers = make_headers(&[("x-fastly-request-id", "abc123")]);
    let result = fingerprint_from_response(&headers, None, 200);
    assert!(result.waf_types().contains(&&WafType::Fastly));
}

#[test]
fn test_display_waf_types() {
    assert_eq!(format!("{}", WafType::Cloudflare), "Cloudflare");
    assert_eq!(format!("{}", WafType::Imperva), "Imperva/Incapsula");
    assert_eq!(format!("{}", WafType::OwaspCrs), "OWASP CRS");
    assert_eq!(
        format!("{}", WafType::Unknown("test".to_string())),
        "Unknown (test)"
    );
}

#[test]
fn test_owasp_crs_detection_by_rule_id() {
    let headers = make_headers(&[]);
    let body = r#"<html><body>ModSecurity: Access denied with code 403. id "941110"</body></html>"#;
    let result = fingerprint_from_response(&headers, Some(body), 403);
    assert!(result.waf_types().contains(&&WafType::OwaspCrs));
}

#[test]
fn test_owasp_crs_detection_by_name() {
    let headers = make_headers(&[]);
    let body = "Blocked by OWASP_CRS/3.3.4";
    let result = fingerprint_from_response(&headers, Some(body), 403);
    assert!(result.waf_types().contains(&&WafType::OwaspCrs));
}

#[test]
fn test_owasp_crs_plus_modsecurity_dual_detect() {
    let headers = make_headers(&[("server", "Apache/2.4 (ModSecurity)")]);
    let body = r#"ModSecurity: Access denied. id "941100" OWASP_CRS/3.3.4"#;
    let result = fingerprint_from_response(&headers, Some(body), 403);
    // Should detect both ModSecurity engine and OWASP CRS ruleset
    assert!(result.waf_types().contains(&&WafType::OwaspCrs));
    assert!(result.waf_types().contains(&&WafType::ModSecurity));
}
